# This runs on the Docker Host

version: '3'

services:
  predictord:
    container_name: predictord
    image: registry:5000/predictord:1.0.15
    logging:
      driver: syslog
      options:
        tag: predictord
    environment:
      STAGE: PRD
      VERSION: 1.0.15
      
