# This runs on the Docker Host

version: '3'

services:
  cloudmetricsd:
    container_name: cloudmetricsd
    image: registry:5000/cloudmetricsd:1.0.27
    logging:
      driver: syslog
      options:
        tag: "cloudmetricsd"
    environment:
      STAGE: PRD
      VERSION: 1.0.27
      VERBOSE: 'True'
      TELEGRAF_ENDPOINT: 192.168.1.180
    devices:
      - dev/snd:dev/snd  
      