# This runs on the Docker Host

version: '3'

services:
  metminimisc-service:
    container_name: metminimisc-service
    image: registry:5000/metminimisc-service:1.0.7
    logging:
      driver: syslog
      options:
        tag: metminimisc-service
    environment:
      STAGE: PRD
      VERSION: 1.0.7
    ports:
      - "9505:9505"
